version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tec-postgres
    environment:
      POSTGRES_DB: tecdb
      POSTGRES_USER: tecadmin
      POSTGRES_PASSWORD: dev-password-123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - tec-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tecadmin -d tecdb"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: tec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tec-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # The Elidoras Codex Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tec-app
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://tecadmin:dev-password-123@postgres:5432/tecdb
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key-here}
      AZURE_SEARCH_ENDPOINT: ${AZURE_SEARCH_ENDPOINT:-}
      AZURE_SEARCH_API_KEY: ${AZURE_SEARCH_API_KEY:-}
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: tec-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elidorascodex.org
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - tec-network
    profiles:
      - dev-tools

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tec-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - tec-network
    profiles:
      - dev-tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  node_modules:
    driver: local

networks:
  tec-network:
    driver: bridge
